Pass SSL configuration arguments to Async Api Client (#1655)
* Fix AsyncRestClient Missing SSL Params

Configuration arguments aren't correctly passed into the async rest client. This can result in ssl errors even after we've disabled ssl verification in the configuration.

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

* Update rest.j2 e54f10bc336816e80160b82b3de98bc8a7c76133